# Use an official Nginx image to serve static files
FROM nginx:alpine

# Copy static files from the current directory to Nginx's html directory
COPY . /usr/share/nginx/html

# Expose port 80 to allow access to the app
EXPOSE 80
