version: '3.8'

services:
  frontend:
    build:
      context: ./frontend # Path to your frontend folder
      dockerfile: Dockerfile # Specify if necessary
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container

  backend:
    build:
      context: ./lambda # Path to your lambda folder
      dockerfile: Dockerfile # Ensure this matches the filename exactly
    environment:
      DYNAMODB_TABLE_NAME: "TypingTestResults" # Example environment variable
